---
services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    network_mode: host
    environment:
      - PORT=80

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    network_mode: host
    environment:
      - PORT=3000